image: devshawn/gitlab-dind-node-yarn

stages:
  - build
  - test
  - publish

cache:
  paths:
  - node_modules/
  - client/node_modules/

build:
  stage: build
  script:
    - yarn install
    - cd client/ && yarn install && cd ..
    - yarn run build
  artifacts:
      expire_in: 1 week
      paths:
      - dist/

test:
  stage: test
  script: yarn run test

publish:
  stage: publish
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t password-generator .
    - docker tag password-generator $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:10}
    - docker tag password-generator $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE
  dependencies:
    - build