image: devshawn/gitlab-dind-node-yarn

stages:
  - build
  - test
  - publish

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
    - yarn install
    - cd client/ && yarn install && cd ..
    - yarn run build
  artifacts:
      expire_in: 1 week
      paths:
      - dist/

test:
  stage: test
  script: yarn run test

